---
- name: Configure virtuozzo mds servers
#  hosts: virtuozzo7
#  tasks:
#  - name: inet add
#    shell: "prlsrvctl net add inet --type bridged -i bond0.31"
  hosts: virtuozzo7[0]
  tasks:
  - name: deploy first mds
#    debug: msg="{{item.key}}: {{item.value}}"
    shell: "echo 'Pa$$w0rd'|vstorage -c {{ my_cluster_name }} make-mds -I -a {{ cluster_vlan_network.address }} -r /vstorage/{{ my_cluster_name }}-{{ my_mds_index }}/mds -P"
  - systemd: 
      name: vstorage-mdsd.target
      state: restarted

- hosts: virtuozzo7[1:2]     
  tasks:
  - name: deploy the rest mds
    shell: "echo 'Pa$$w0rd'|vstorage -c {{ my_cluster_name }} auth-node -b 192.168.1.22 -P; vstorage -c {{ my_cluster_name }} make-mds -a {{ cluster_vlan_network.address }} -r /vstorage/{{ my_cluster_name }}-{{ my_mds_index }}/mds"
  - systemd:
      name: vstorage-mdsd.target
      state: restarted

- hosts: virtuozzo7[3:]
  tasks:
  - name: auth servers w/o mds  
    shell: "echo 'Pa$$w0rd'|vstorage -c {{ my_cluster_name }} auth-node -b 192.168.1.22 -P"

#- hosts: virtuozzo7
#  tasks:
#  - name : install mc
#    shell: "yum install -y mc"
